### ISSUE TITLE
Can't run scene cause of errors

### ISSUE THREAD

**Issue by markus-weiss** [maajor/NeuralNetworkPostProcessing#4]
Hello maajor,
for my master thesis maybe i want to us your plugin for a study. But now I download your code from GitHub and follow your instructions in the documentation.pdf till "click play button".  The engine switched automatically in pause-mode and the console was full of the follow errors:

`Thread group count is above the maximum allowed limit. Maximum allowed thread group count is 65535.
UnityEngine.ComputeShader:Dispatch(Int32, Int32, Int32, Int32)
NNPP.ReLU:Run(Object[]) (at Assets/NNPostProcessing/Scripts/NNLayers/ReLU.cs:37)
NNPP.NNModel:Predict(RenderTexture) (at Assets/NNPostProcessing/Scripts/NNModel.cs:108)
NNPP.NNPostProcessingEffect:OnRenderImage(RenderTexture, RenderTexture) (at Assets/NNPostProcessing/Scripts/NNPostProcessingEffect.cs:32)`

![ScreenShotNeuralStyleTransfer](https://user-images.githubusercontent.com/37873311/67942202-9eaa1d80-fbd7-11e9-99c1-772a2a0d5ed9.PNG)

I don't know how to fix that. I hope u can help me with this errors.

Best regards Markus

**Comment by maajor** [comment]
Hi Markus,
I checked that it is because of new version of Unity. I have submitted a fix, please check it out.

Best Regards,
MYD

**Comment by Vahe987** [comment]
Hi @maajor , 
The bug is still present:

Thread group count is above the maximum allowed limit. Maximum allowed thread group count is 65535.
UnityEngine.ComputeShader:Dispatch(Int32, Int32, Int32, Int32)
NNPP.BatchNormalization:Run(Object[]) (at Assets/NNPostProcessing/Scripts/NNLayers/BatchNormalization.cs:80)
NNPP.NNModel:Predict(RenderTexture) (at Assets/NNPostProcessing/Scripts/NNModel.cs:108)
NNPP.NNPostProcessingEffect:OnRenderImage(RenderTexture, RenderTexture) (at Assets/NNPostProcessing/Scripts/NNPostProcessingEffect.cs:32)

My Unity version is 2019.2.12f1
